/**
 * Phase 0.C — cut the oracle's <style> block into src/styles/*.css with ZERO
 * visual edits.
 *
 * The split is mechanical on purpose: it slices `legacy/index.html` at the
 * `/* ---------- name ---------- *\/` comment boundaries that are already in
 * the file and writes each slice out verbatim. `--check` re-concatenates the
 * generated files in import order and asserts the result is byte-identical to
 * the oracle, so a stray edit fails instead of silently drifting.
 *
 *   node scripts/split-css.mjs          # write
 *   node scripts/split-css.mjs --check  # verify only
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..', '..', '..');
const oraclePath = join(repoRoot, 'legacy', 'index.html');
const outDir = join(here, '..', 'src', 'styles');

/**
 * Block name -> output file. Order is source order and must stay source order:
 * the cascade in `index.html` depends on it.
 */
const FILES = [
  ['@head', 'tokens.css'], // the pre-font <style> plus :root, reset, utilities
  ['global fx canvas', 'fx.css'],
  ['top bar', 'topbar.css'],
  ['tape', 'tape.css'],
  ['layout', 'layout.css'],
  ['king of the hill', 'koth.css'],
  ['board', 'board.css'],
  ['coin card', 'card.css'],
  ['flash', 'flash.css'],
  ['token page', 'token.css'],
  ['chat drawer', 'chat.css'],
  ['create modal', 'modal.css'],
  ['toast / footer', 'toast.css'],
  ['rank widget (header)', 'rank.css'],
  ['rewards page', 'rewards.css'],
  ['footer sol', 'footer-sol.css'],
  ['wallet', 'wallet.css'],
  ['launch cta (sort strip)', 'launch-cta.css'],
  ['footer bits', 'footer.css'],
  ['stat quad', 'quad.css'],
  ['profile', 'profile.css'],
  ['settings', 'settings.css'],
  ['tape hover card', 'tape-pop.css'],
  ['profile strip extras', 'profile-strip.css'],
  ['claim modal', 'claim.css'],
  ['how it works wizard', 'wizard.css'],
  ['network picker', 'netpicker.css'],
  ['launch flow', 'launch.css'],
  ['cashback', 'cashback.css'],
  ['staking', 'staking.css'],
  ['profiles: identity, follow, shoutbox, friends', 'social.css'],
  ['rank up', 'rankup.css'],
  ['achievements', 'achievements.css'],
  ['streak chip, position, fill flash', 'streak.css'],
  ['first visit', 'hello.css'],
  ['responsive', 'responsive.css'],
];

function readOracleCss() {
  const html = readFileSync(oraclePath, 'utf8');
  const head = html.match(/<style>(body\{margin:0\}[^<]*)<\/style>/);
  if (!head) throw new Error('oracle: the pre-font <style> block moved');
  const main = html.match(/<style>\n(:root\{[\s\S]*?)\n<\/style>/);
  if (!main) throw new Error('oracle: the main <style> block moved');
  return { head: head[1], main: main[1] };
}

function slice(css) {
  const lines = css.split('\n');
  const marks = [];
  lines.forEach((line, i) => {
    const m = line.match(/^\/\* -+ (.+?) -+ \*\/$/);
    if (m) marks.push({ name: m[1], line: i });
  });
  const blocks = [{ name: '@head', body: lines.slice(0, marks[0].line).join('\n') }];
  marks.forEach((mark, i) => {
    const end = i + 1 < marks.length ? marks[i + 1].line : lines.length;
    blocks.push({ name: mark.name, body: lines.slice(mark.line, end).join('\n') });
  });
  return blocks;
}

const { head, main } = readOracleCss();
const blocks = slice(main);

if (blocks.length !== FILES.length) {
  throw new Error(`oracle has ${blocks.length} css blocks, the map has ${FILES.length}`);
}
blocks.forEach((b, i) => {
  if (b.name !== FILES[i][0]) {
    throw new Error(`block ${i} is "${b.name}", the map expects "${FILES[i][0]}"`);
  }
});

/** `@head` also carries the tiny pre-font <style> that precedes everything. */
const bodies = blocks.map((b, i) => (i === 0 ? head + '\n' + b.body : b.body));

const check = process.argv.includes('--check');
const problems = [];

bodies.forEach((body, i) => {
  const file = join(outDir, FILES[i][1]);
  // Always terminate: a block that ends on a blank line joins to "…\n", and
  // that trailing newline is the separator into the blank line, not the file
  // terminator. Concatenation has to reproduce both.
  const want = body + '\n';
  if (check) {
    if (!existsSync(file)) {
      problems.push(`missing ${FILES[i][1]}`);
      return;
    }
    if (readFileSync(file, 'utf8') !== want) problems.push(`drifted ${FILES[i][1]}`);
  } else {
    mkdirSync(outDir, { recursive: true });
    writeFileSync(file, want);
  }
});

const indexCss =
  `/*\n` +
  ` * Phase 0.C pixel lock.\n` +
  ` *\n` +
  ` * One file per CSS comment block in the oracle, imported in oracle order so\n` +
  ` * the cascade is unchanged. The files are generated by scripts/split-css.mjs\n` +
  ` * and verified byte-for-byte by \`pnpm --filter @stonkz/web css:check\`; edit\n` +
  ` * the oracle first if a rule genuinely has to change.\n` +
  ` */\n` +
  FILES.map(([, f]) => `@import './${f}';`).join('\n') +
  '\n';

const indexPath = join(outDir, 'index.css');
if (check) {
  if (!existsSync(indexPath) || readFileSync(indexPath, 'utf8') !== indexCss) {
    problems.push('drifted index.css');
  }
} else {
  writeFileSync(indexPath, indexCss);
}

if (check) {
  if (problems.length) {
    console.error('CSS pixel lock FAILED:\n  ' + problems.join('\n  '));
    process.exit(1);
  }
  console.log(`CSS pixel lock ok — ${FILES.length} files match legacy/index.html`);
} else {
  console.log(`wrote ${FILES.length} files + index.css to src/styles`);
}
