//! Emits `programs/parity-vectors.json` from the Rust settlement math.
//!
//! That file is the single table three implementations are held to: this
//! program, the TypeScript simulate helper the API and the launch preview both
//! import (`programs/curve-sim.ts`), and the Solidity mirror
//! (`programs/evm/src/CurveMath.sol`). If any of the three drifts, its own test
//! suite fails against these vectors rather than the drift being discovered in
//! production by a user whose quote did not match their fill.
//!
//! The layout is **column-oriented** — one array per field rather than an array
//! of objects. Foundry's JSON cheatcodes cannot express a `[*]` wildcard, so a
//! row-oriented file would force the Solidity side into one cheatcode call per
//! cell. Columns keep all three readers to a handful of calls.
//!
//! Every number is a decimal **string**, because the vectors deliberately
//! include `u64::MAX` and 30-digit `k` values that a JSON number cannot carry
//! exactly. The two genuinely small fields (`baseDecimals`, bps) stay numeric.
//!
//! Regenerate with `cargo test -p launchpad --lib parity`.

use crate::constants::*;
use crate::math::*;
use std::fmt::Write as _;

/// `programs/parity-vectors.json`, resolved from the crate root so it lands in
/// the same place no matter where cargo is invoked from.
fn out_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .join("parity-vectors.json")
}

struct Case {
    supply: u64,
    price_1e6: u64,
    base_decimals: u8,
}

const CASES: [Case; 5] = [
    // 1B supply against a $1.00 6-decimal stable — the common case.
    Case {
        supply: 1_000_000_000,
        price_1e6: 1_000_000,
        base_decimals: 6,
    },
    // 1B against a $200 9-decimal base (wrapped SOL).
    Case {
        supply: 1_000_000_000,
        price_1e6: 200_000_000,
        base_decimals: 9,
    },
    // 500M against a $3,000 18-decimal base (WETH on Robinhood Chain).
    Case {
        supply: 500_000_000,
        price_1e6: 3_000_000_000,
        base_decimals: 18,
    },
    // 1M supply, expensive few-decimal base — the tightest truncation case,
    // and the one that caught the virtual_base rounding direction.
    Case {
        supply: 1_000_000,
        price_1e6: 4_312_500_000,
        base_decimals: 8,
    },
    // 1T supply, cheap 5-decimal base — the largest k.
    Case {
        supply: 1_000_000_000_000,
        price_1e6: 10,
        base_decimals: 5,
    },
];

/// A column of decimal strings.
fn col_str<T: std::fmt::Display>(name: &str, vals: &[T], indent: &str, last: bool) -> String {
    let body = vals
        .iter()
        .map(|v| format!("\"{v}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "{indent}\"{name}\": [{body}]{}\n",
        if last { "" } else { "," }
    )
}

/// A column of raw JSON values (numbers, booleans).
fn col_raw<T: std::fmt::Display>(name: &str, vals: &[T], indent: &str, last: bool) -> String {
    let body = vals
        .iter()
        .map(|v| v.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "{indent}\"{name}\": [{body}]{}\n",
        if last { "" } else { "," }
    )
}

#[test]
fn parity_vectors() {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str("  \"$comment\": \"Generated by `cargo test -p launchpad --lib parity`. Column-oriented, all large numbers as decimal strings. Do not hand-edit.\",\n");
    out.push_str("  \"gradMcapUsd1e6\": \"69000000000\",\n");

    /* ------------------------------------------------------------- fee split */

    let fees: [u64; 14] = [
        0,
        1,
        2,
        3,
        7,
        9,
        10,
        99,
        100,
        12_345,
        999_999,
        1_000_000_007,
        18_446_744_073,
        u64::MAX,
    ];
    let shares: Vec<FeeShares> = fees.iter().map(|f| split_fee(*f)).collect();
    out.push_str("  \"feeSplit\": {\n");
    out.push_str(&col_str("fee", &fees, "    ", false));
    out.push_str(&col_str(
        "protocol",
        &shares.iter().map(|s| s.protocol).collect::<Vec<_>>(),
        "    ",
        false,
    ));
    out.push_str(&col_str(
        "ops",
        &shares.iter().map(|s| s.stonkz_ops).collect::<Vec<_>>(),
        "    ",
        false,
    ));
    out.push_str(&col_str(
        "burn",
        &shares.iter().map(|s| s.burn).collect::<Vec<_>>(),
        "    ",
        false,
    ));
    out.push_str(&col_str(
        "creatorBucket",
        &shares.iter().map(|s| s.creator_bucket).collect::<Vec<_>>(),
        "    ",
        true,
    ));
    out.push_str("  },\n");

    /* -------------------------------------------------------- bucket split */

    let bs: [(u64, u64, u64); 8] = [
        (1_000_000, 0, 1_000_000_000),
        (1_000_000, 1, 1_000_000_000),
        (1_000_000, 500_000_000, 1_000_000_000),
        (1_000_000, 1_000_000_000, 1_000_000_000),
        (1_000_000, 2_000_000_000, 1_000_000_000),
        (7, 3, 10),
        (1, 1, 1),
        (0, 5, 10),
    ];
    let splits: Vec<BucketSplit> = bs
        .iter()
        .map(|(b, s, c)| split_creator_bucket(*b, *s, *c))
        .collect();
    out.push_str("  \"creatorBucketSplit\": {\n");
    out.push_str(&col_str(
        "bucket",
        &bs.iter().map(|x| x.0).collect::<Vec<_>>(),
        "    ",
        false,
    ));
    out.push_str(&col_str(
        "eligibleStaked",
        &bs.iter().map(|x| x.1).collect::<Vec<_>>(),
        "    ",
        false,
    ));
    out.push_str(&col_str(
        "circulating",
        &bs.iter().map(|x| x.2).collect::<Vec<_>>(),
        "    ",
        false,
    ));
    out.push_str(&col_str(
        "creator",
        &splits.iter().map(|s| s.creator).collect::<Vec<_>>(),
        "    ",
        false,
    ));
    out.push_str(&col_str(
        "stakers",
        &splits.iter().map(|s| s.stakers).collect::<Vec<_>>(),
        "    ",
        true,
    ));
    out.push_str("  },\n");

    /* ------------------------------------------------------------- cashback */

    let mut cb_base = Vec::new();
    let mut cb_elapsed = Vec::new();
    let mut cb_on = Vec::new();
    let mut cb_eff = Vec::new();
    for base in [100u16, 250, 500] {
        for elapsed in [0i64, 1, 75, 150, 299, 300, 301, 100_000] {
            cb_base.push(base);
            cb_elapsed.push(elapsed);
            cb_on.push(true);
            cb_eff.push(eff_fee_bps(base, true, 0, elapsed));
        }
        // A non-cashback coin is flat at the creator's own fee.
        cb_base.push(base);
        cb_elapsed.push(0);
        cb_on.push(false);
        cb_eff.push(eff_fee_bps(base, false, 0, 0));
    }
    out.push_str("  \"effFeeBps\": {\n");
    out.push_str(&col_raw("baseBps", &cb_base, "    ", false));
    out.push_str(&col_raw("elapsedSecs", &cb_elapsed, "    ", false));
    out.push_str(&col_raw("cashback", &cb_on, "    ", false));
    out.push_str(&col_raw("effBps", &cb_eff, "    ", true));
    out.push_str("  },\n");

    /* --------------------------------------------------------------- curves */

    let _ = write!(out, "  \"curveCount\": {},\n", CASES.len());
    out.push_str("  \"curves\": [\n");

    for (ci, c) in CASES.iter().enumerate() {
        let supply_atoms = c.supply * 10u64.pow(TOKEN_DECIMALS as u32);
        let p = derive_curve(supply_atoms, c.price_1e6, c.base_decimals).expect("derives");

        let mut st = CurveState {
            virtual_base: p.virtual_base,
            virtual_token: p.virtual_token,
            real_base: 0,
            real_token: p.tokens_for_sale,
            k: p.k,
        };
        let mut held: u64 = 0;

        let (mut side, mut fee_bps_c, mut amount_in) = (vec![], vec![], vec![]);
        let (mut s_vb, mut s_vt, mut s_rb, mut s_rt) = (vec![], vec![], vec![], vec![]);
        let (mut gross, mut fee_c, mut net, mut tokens_out) = (vec![], vec![], vec![], vec![]);
        let (mut complete, mut proto, mut ops_c, mut burn_c, mut bucket_c) =
            (vec![], vec![], vec![], vec![], vec![]);

        // A fixed script: buys of growing size, two sells, then a buy that has
        // to be capped because it asks for more than the curve can deliver.
        let unit = (p.grad_mcap_base / 2_000).max(1) as u64;
        let script: [(bool, u64, u16); 9] = [
            (true, unit, 100),
            (true, unit * 7, 250),
            (true, unit * 40, 500),
            (false, 0, 250),
            (true, unit * 120, 137),
            (false, 0, 500),
            (true, unit * 400, 419),
            (true, unit * 900, 100),
            (true, u64::MAX / 4, 100),
        ];

        for (is_buy, amount, bps) in script {
            // Record the state each fill is quoted against, so a reader that
            // has drifted fails at the fill that caused it.
            let (vb0, vt0, rb0, rt0) = (
                st.virtual_base,
                st.virtual_token,
                st.real_base,
                st.real_token,
            );
            if is_buy {
                let Some(f) = buy_quote(&st, bps, amount) else {
                    continue;
                };
                let s = split_fee(f.fee);
                side.push("buy");
                amount_in.push(amount);
                gross.push(f.gross_base);
                fee_c.push(f.fee);
                net.push(f.net_base);
                tokens_out.push(f.tokens_out);
                complete.push(f.curve_complete);
                proto.push(s.protocol);
                ops_c.push(s.stonkz_ops);
                burn_c.push(s.burn);
                bucket_c.push(s.creator_bucket);
                st.virtual_base += f.net_base as u128;
                st.virtual_token -= f.tokens_out as u128;
                st.real_base += f.net_base;
                st.real_token -= f.tokens_out;
                held += f.tokens_out;
            } else {
                let amount = held / 3;
                let Some(f) = sell_quote(&st, bps, amount) else {
                    continue;
                };
                let s = split_fee(f.fee);
                side.push("sell");
                amount_in.push(amount);
                gross.push(f.gross_base);
                fee_c.push(f.fee);
                net.push(f.net_base);
                tokens_out.push(0);
                complete.push(false);
                proto.push(s.protocol);
                ops_c.push(s.stonkz_ops);
                burn_c.push(s.burn);
                bucket_c.push(s.creator_bucket);
                st.virtual_base -= f.gross_base as u128;
                st.virtual_token += amount as u128;
                st.real_base -= f.gross_base;
                st.real_token += amount;
                held -= amount;
            }
            fee_bps_c.push(bps);
            s_vb.push(vb0);
            s_vt.push(vt0);
            s_rb.push(rb0);
            s_rt.push(rt0);
        }

        let _ = write!(
            out,
            "    {{\n      \"supply\": \"{}\",\n      \"supplyAtoms\": \"{}\",\n      \"price1e6\": \"{}\",\n      \"baseDecimals\": {},\n      \"tokensForSale\": \"{}\",\n      \"lpReserve\": \"{}\",\n      \"virtualToken\": \"{}\",\n      \"virtualBase\": \"{}\",\n      \"k\": \"{}\",\n      \"gradMcapBase\": \"{}\",\n      \"fills\": {{\n",
            c.supply, supply_atoms, c.price_1e6, c.base_decimals,
            p.tokens_for_sale, p.lp_reserve, p.virtual_token, p.virtual_base, p.k, p.grad_mcap_base
        );
        let body = format!("\"{}\"", side.join("\", \""));
        let _ = write!(out, "        \"side\": [{body}],\n");
        out.push_str(&col_raw("feeBps", &fee_bps_c, "        ", false));
        out.push_str(&col_str("amountIn", &amount_in, "        ", false));
        out.push_str(&col_str("virtualBase", &s_vb, "        ", false));
        out.push_str(&col_str("virtualToken", &s_vt, "        ", false));
        out.push_str(&col_str("realBase", &s_rb, "        ", false));
        out.push_str(&col_str("realToken", &s_rt, "        ", false));
        out.push_str(&col_str("grossBase", &gross, "        ", false));
        out.push_str(&col_str("fee", &fee_c, "        ", false));
        out.push_str(&col_str("netBase", &net, "        ", false));
        out.push_str(&col_str("tokensOut", &tokens_out, "        ", false));
        out.push_str(&col_raw("curveComplete", &complete, "        ", false));
        out.push_str(&col_str("protocol", &proto, "        ", false));
        out.push_str(&col_str("ops", &ops_c, "        ", false));
        out.push_str(&col_str("burn", &burn_c, "        ", false));
        out.push_str(&col_str("creatorBucket", &bucket_c, "        ", true));
        out.push_str("      },\n");

        let mcap = mcap_base(&st, supply_atoms).unwrap();
        let usd = mcap_usd_1e6(mcap, c.price_1e6, c.base_decimals).unwrap();
        let _ = write!(
            out,
            "      \"final\": {{\n        \"virtualBase\": \"{}\",\n        \"virtualToken\": \"{}\",\n        \"realBase\": \"{}\",\n        \"realToken\": \"{}\",\n        \"mcapBase\": \"{}\",\n        \"mcapUsd1e6\": \"{}\"\n      }}\n    }}{}\n",
            st.virtual_base, st.virtual_token, st.real_base, st.real_token, mcap, usd,
            if ci + 1 == CASES.len() { "" } else { "," }
        );
    }
    out.push_str("  ]\n}\n");

    std::fs::write(out_path(), &out).expect("write parity vectors");

    // The vectors are only useful if they are self-consistent, so check the
    // invariants here rather than trusting the writer.
    for c in CASES.iter() {
        let supply_atoms = c.supply * 10u64.pow(TOKEN_DECIMALS as u32);
        let p = derive_curve(supply_atoms, c.price_1e6, c.base_decimals).unwrap();
        assert_eq!(p.tokens_for_sale + p.lp_reserve, supply_atoms);
        assert_eq!(p.k, p.virtual_base * p.virtual_token);
    }
}
