//! Emits `programs/parity-vectors.json` from the Rust settlement math.
//!
//! That file is the single table three implementations are held to: this
//! program, the TypeScript simulate helper the API and the launch preview both
//! import (`programs/curve-sim.ts`), and the Solidity mirror
//! (`programs/evm/src/CurveMath.sol`). If any of the three drifts, its own test
//! suite fails against these vectors rather than the drift being discovered in
//! production by a user whose quote did not match their fill.
//!
//! Regenerate with `cargo test -p launchpad --lib parity`.

use crate::constants::*;
use crate::math::*;
use std::fmt::Write as _;

/// `programs/parity-vectors.json`, resolved from the crate root so it lands in
/// the same place no matter where cargo is invoked from.
fn out_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .join("parity-vectors.json")
}

struct Case {
    supply: u64,
    price_1e6: u64,
    base_decimals: u8,
}

const CASES: [Case; 5] = [
    // 1B supply against a $1.00 6-decimal stable — the common case.
    Case { supply: 1_000_000_000, price_1e6: 1_000_000, base_decimals: 6 },
    // 1B against a $200 9-decimal base (wrapped SOL).
    Case { supply: 1_000_000_000, price_1e6: 200_000_000, base_decimals: 9 },
    // 500M against an 18-decimal base (the EVM default, and RH stock tokens).
    Case { supply: 500_000_000, price_1e6: 3_000_000_000, base_decimals: 18 },
    // 1M supply, expensive few-decimal base — the tightest truncation case,
    // and the one that caught the virtual_base rounding direction.
    Case { supply: 1_000_000, price_1e6: 4_312_500_000, base_decimals: 8 },
    // 1T supply, cheap 5-decimal base — the largest k.
    Case { supply: 1_000_000_000_000, price_1e6: 10, base_decimals: 5 },
];

#[test]
fn parity_vectors() {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str("  \"$comment\": \"Generated by cargo test -p launchpad --lib parity. Do not hand-edit.\",\n");
    out.push_str("  \"gradMcapUsd1e6\": \"69000000000\",\n");

    /* ------------------------------------------------------------- fee split */
    out.push_str("  \"feeSplit\": [\n");
    let fees: [u64; 14] = [
        0, 1, 2, 3, 7, 9, 10, 99, 100, 12_345, 999_999, 1_000_000_007, 18_446_744_073, u64::MAX,
    ];
    for (i, f) in fees.iter().enumerate() {
        let s = split_fee(*f);
        let _ = write!(
            out,
            "    {{ \"fee\": \"{}\", \"protocol\": \"{}\", \"ops\": \"{}\", \"creatorBucket\": \"{}\" }}{}\n",
            f,
            s.protocol,
            s.stonkz_ops,
            s.creator_bucket,
            if i + 1 == fees.len() { "" } else { "," }
        );
    }
    out.push_str("  ],\n");

    /* -------------------------------------------------------- bucket split */
    out.push_str("  \"creatorBucketSplit\": [\n");
    let bs: [(u64, u64, u64); 8] = [
        (1_000_000, 0, 1_000_000_000),
        (1_000_000, 1, 1_000_000_000),
        (1_000_000, 500_000_000, 1_000_000_000),
        (1_000_000, 1_000_000_000, 1_000_000_000),
        (1_000_000, 2_000_000_000, 1_000_000_000),
        (7, 3, 10),
        (1, 1, 1),
        (0, 5, 10),
    ];
    for (i, (bucket, staked, circ)) in bs.iter().enumerate() {
        let r = split_creator_bucket(*bucket, *staked, *circ);
        let _ = write!(
            out,
            "    {{ \"bucket\": \"{}\", \"eligibleStaked\": \"{}\", \"circulating\": \"{}\", \"creator\": \"{}\", \"stakers\": \"{}\" }}{}\n",
            bucket, staked, circ, r.creator, r.stakers,
            if i + 1 == bs.len() { "" } else { "," }
        );
    }
    out.push_str("  ],\n");

    /* ------------------------------------------------------------- cashback */
    out.push_str("  \"effFeeBps\": [\n");
    let mut rows = Vec::new();
    for base in [100u16, 250, 500] {
        for elapsed in [0i64, 1, 75, 150, 299, 300, 301, 100_000] {
            rows.push((base, elapsed, eff_fee_bps(base, true, 0, elapsed)));
        }
        rows.push((base, 0, eff_fee_bps(base, false, 0, 0)));
    }
    for (i, (base, elapsed, bps)) in rows.iter().enumerate() {
        let _ = write!(
            out,
            "    {{ \"baseBps\": {}, \"elapsedSecs\": {}, \"cashback\": {}, \"effBps\": {} }}{}\n",
            base,
            elapsed,
            i % 9 != 8,
            bps,
            if i + 1 == rows.len() { "" } else { "," }
        );
    }
    out.push_str("  ],\n");

    /* --------------------------------------------------------------- curves */
    out.push_str("  \"curves\": [\n");
    for (ci, c) in CASES.iter().enumerate() {
        let supply_atoms = c.supply * 10u64.pow(TOKEN_DECIMALS as u32);
        let p = derive_curve(supply_atoms, c.price_1e6, c.base_decimals).expect("derives");
        let _ = write!(
            out,
            "    {{\n      \"supply\": \"{}\", \"supplyAtoms\": \"{}\", \"price1e6\": \"{}\", \"baseDecimals\": {},\n      \"tokensForSale\": \"{}\", \"lpReserve\": \"{}\", \"virtualToken\": \"{}\", \"virtualBase\": \"{}\",\n      \"k\": \"{}\", \"gradMcapBase\": \"{}\",\n      \"fills\": [\n",
            c.supply, supply_atoms, c.price_1e6, c.base_decimals,
            p.tokens_for_sale, p.lp_reserve, p.virtual_token, p.virtual_base, p.k, p.grad_mcap_base
        );

        let mut st = CurveState {
            virtual_base: p.virtual_base,
            virtual_token: p.virtual_token,
            real_base: 0,
            real_token: p.tokens_for_sale,
            k: p.k,
        };
        let mut held: u64 = 0;
        let mut lines: Vec<String> = Vec::new();

        // A fixed script: buys of growing size, two sells, then a buy that has
        // to be capped because it asks for more than the curve can deliver.
        let unit = (p.grad_mcap_base / 2_000).max(1) as u64;
        let script: [(bool, u64, u16); 9] = [
            (true, unit, 100),
            (true, unit * 7, 250),
            (true, unit * 40, 500),
            (false, 0, 250),
            (true, unit * 120, 137),
            (false, 0, 500),
            (true, unit * 400, 419),
            (true, unit * 900, 100),
            (true, u64::MAX / 4, 100),
        ];

        for (is_buy, amount, fee_bps) in script {
            if is_buy {
                let Some(f) = buy_quote(&st, fee_bps, amount) else { continue };
                let s = split_fee(f.fee);
                lines.push(format!(
                    "        {{ \"side\": \"buy\", \"feeBps\": {}, \"amountIn\": \"{}\", \"virtualBase\": \"{}\", \"virtualToken\": \"{}\", \"realToken\": \"{}\", \"realBase\": \"{}\", \"grossBase\": \"{}\", \"fee\": \"{}\", \"netBase\": \"{}\", \"tokensOut\": \"{}\", \"curveComplete\": {}, \"protocol\": \"{}\", \"ops\": \"{}\", \"creatorBucket\": \"{}\" }}",
                    fee_bps, amount, st.virtual_base, st.virtual_token, st.real_token, st.real_base,
                    f.gross_base, f.fee, f.net_base, f.tokens_out, f.curve_complete,
                    s.protocol, s.stonkz_ops, s.creator_bucket
                ));
                st.virtual_base += f.net_base as u128;
                st.virtual_token -= f.tokens_out as u128;
                st.real_base += f.net_base;
                st.real_token -= f.tokens_out;
                held += f.tokens_out;
            } else {
                let amount = held / 3;
                let Some(f) = sell_quote(&st, fee_bps, amount) else { continue };
                let s = split_fee(f.fee);
                lines.push(format!(
                    "        {{ \"side\": \"sell\", \"feeBps\": {}, \"amountIn\": \"{}\", \"virtualBase\": \"{}\", \"virtualToken\": \"{}\", \"realToken\": \"{}\", \"realBase\": \"{}\", \"grossBase\": \"{}\", \"fee\": \"{}\", \"netBase\": \"{}\", \"tokensOut\": \"0\", \"curveComplete\": false, \"protocol\": \"{}\", \"ops\": \"{}\", \"creatorBucket\": \"{}\" }}",
                    fee_bps, amount, st.virtual_base, st.virtual_token, st.real_token, st.real_base,
                    f.gross_base, f.fee, f.net_base,
                    s.protocol, s.stonkz_ops, s.creator_bucket
                ));
                st.virtual_base -= f.gross_base as u128;
                st.virtual_token += amount as u128;
                st.real_base -= f.gross_base;
                st.real_token += amount;
                held -= amount;
            }
        }

        out.push_str(&lines.join(",\n"));
        let mcap = mcap_base(&st, supply_atoms).unwrap();
        let usd = mcap_usd_1e6(mcap, c.price_1e6, c.base_decimals).unwrap();
        let _ = write!(
            out,
            "\n      ],\n      \"final\": {{ \"virtualBase\": \"{}\", \"virtualToken\": \"{}\", \"realBase\": \"{}\", \"realToken\": \"{}\", \"mcapBase\": \"{}\", \"mcapUsd1e6\": \"{}\" }}\n    }}{}\n",
            st.virtual_base, st.virtual_token, st.real_base, st.real_token, mcap, usd,
            if ci + 1 == CASES.len() { "" } else { "," }
        );
    }
    out.push_str("  ]\n}\n");

    std::fs::write(out_path(), &out).expect("write parity vectors");

    // The vectors are only useful if they are self-consistent, so assert the
    // invariants here too rather than trusting the writer.
    assert!(out.contains("\"creatorBucket\""));
    for c in CASES.iter() {
        let supply_atoms = c.supply * 10u64.pow(TOKEN_DECIMALS as u32);
        let p = derive_curve(supply_atoms, c.price_1e6, c.base_decimals).unwrap();
        assert_eq!(p.tokens_for_sale + p.lp_reserve, supply_atoms);
        assert_eq!(p.k, p.virtual_base * p.virtual_token);
    }
}
